name: Get New Comment

on:
  workflow_call:
    inputs:
      php:
        default: "7.0"
        type: string

jobs:
  get-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Comment
        id: comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, issue, comment } = context.payload;

            console.log(`New comment: ${comment.body}`);
            console.log(${{ inputs.php }})
            return comment.body
